### ISSUE TITLE
wideresnet34_10 pretrained weights

### ISSUE THREAD

**Issue by youyuanyi** [boyellow/AdaAD#1]
hello, can you share this pretrained teacher model weights,I didn't find any download links in Readme.md

**Comment by boyellow** [comment]
The Google Drive ID for the pretrained teacher model weights could be found on the [RobustBench](https://github.com/RobustBench/robustbench/blob/master/robustbench/model_zoo/cifar10.py) page. Simply search for the index string "Chen2021LTD_WRN34_10" and you can use this ID to download the weights. Thank you!

**Comment by youyuanyi** [comment]
Thank you very much
